portfolio/MY_PORTFOLIO/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('ajay.urls'))
]

portfolio/ajay/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),

]

portfolio/stockmarket API/stock_market_api/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stocks.urls')),
]

portfolio/stockmarket API/stocks/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('quote/<str:symbol>/', views.get_real_time_quotes, name='get_real_time_quotes'),
    path('historical/<str:symbol>/', views.get_historical_data, name='get_historical_data'),
    path('company/<str:symbol>/', views.get_company_info, name='get_company_info'),
    path('intraday_data/', views.get_intraday_data, name='intraday_data'),
]

portfolio/ajay/models.py
from django.db import models


# HOME SECTION

class Home(models.Model):
    name = models.CharField(max_length=20)
    greet1 = models.CharField(max_length=5)
    greet2 = models.CharField(max_length=5,null=True)
    picture = models.ImageField(upload_to='picture/')
    # save time when modified
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


# ABOUT SECTION

class About(models.Model):
    heading = models.CharField(max_length=50)
    career = models.CharField(max_length=20)
    description = models.TextField(blank=False)
    profile_img = models.ImageField(upload_to='profile/')

    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.career


class Profile(models.Model):
    about = models.ForeignKey(About,
                              on_delete=models.CASCADE)
    social_site = models.CharField(max_length=10)
    link = models.URLField(max_length=200)


# SKILLS SECTION

class Category(models.Model):
    name = models.CharField(max_length=20)

    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Skill'
        verbose_name_plural = 'Skills'

    def __str__(self):
        return self.name


class Skills(models.Model):
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE)
    skill_name = models.CharField(max_length=20)


# PORTFOLIO SECTION

class Portfolio(models.Model):
    image = models.ImageField(upload_to='portfolio/')
    link = models.URLField(max_length=200)

    def __str__(self):
        return f'Portfolio {self.id}'

portfolio/stockmarket API/stocks/models.py
from django.db import models

# Create your models here.

portfolio/ajay/views.py
from django.shortcuts import render
from .models import Home, About, Profile, Category, Skills, Portfolio


def index(request):
    # Home
    home = Home.objects.latest('updated')

    # About
    about = About.objects.latest('updated')
    profiles = Profile.objects.filter(about=about)

    # Skills
    categories = Category.objects.all()

    # Portfolio
    portfolios = Portfolio.objects.all()

    context = {
        'home': home,
        'about': about,
        'profiles': profiles,
        'categories': categories,
        'portfolios': portfolios
    }

    return render(request, 'index.html', context)

portfolio/stockmarket API/stocks/views.py
from django.http import JsonResponse
import requests


def get_real_time_quotes(request, symbol):
    api_key = 'OEDJDXHATRLVCXHG'
    function = 'GLOBAL_QUOTE'
    url = f'https://www.alphavantage.co/query?function={function}&symbol={symbol}&apikey={api_key}'

    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()
        return JsonResponse(data)
    else:
        return JsonResponse({'error': 'Failed to fetch real-time quotes'}, status=500)


def get_historical_data(request, symbol):
    api_key = 'OEDJDXHATRLVCXHG'
    function = 'TIME_SERIES_DAILY'
    outputsize = 'compact'  # Adjust as needed
    datatype = 'json'  # Adjust as needed
    url = f'https://www.alphavantage.co/query?function={function}&symbol={symbol}&outputsize={outputsize}&datatype={datatype}&apikey={api_key}'

    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()
        return JsonResponse(data)
    else:
        return JsonResponse({'error': 'Failed to fetch historical data'}, status=500)


def get_company_info(request, symbol):
    api_key = 'OEDJDXHATRLVCXHG'
    function = 'OVERVIEW'
    url = f'https://www.alphavantage.co/query?function={function}&symbol={symbol}&apikey={api_key}'

    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()
        return JsonResponse(data)
    else:
        return JsonResponse({'error': 'Failed to fetch company information'}, status=500)


def get_intraday_data(request):
    symbol = request.GET.get('symbol')
    interval = request.GET.get('interval', '5min')  # Default to 5-minute interval if not provided

    if symbol:
        api_key = 'OEDJDXHATRLVCXHG'
        function = 'TIME_SERIES_INTRADAY'
        url = f'https://www.alphavantage.co/query?function={function}&symbol={symbol}&interval={interval}&apikey={api_key}'

        response = requests.get(url)
        if response.status_code == 200:
            data = response.json()
            return JsonResponse(data)
        else:
            return JsonResponse({'error': 'Failed to fetch intraday data'}, status=500)
    else:
        return JsonResponse({'error': 'Symbol not provided'}, status=400)

portfolio/ajay/templates/index.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- ===== CSS ===== -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

    <!-- ===== BOX ICONS ===== -->
    <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>

    <title>Portfolio </title>
</head>
<body>
<!--HEADER-->
<header class="l-header">
    <nav class="nav bd-grid">

        <div>
            <a href="#" class="nav__logo">{{ home.name }}</a>
        </div>

        <div class="nav__menu" id="nav-menu">
            <ul class="nav__list">
                <li class="nav__item"><a href="#home" class="nav__link active">Home</a></li>
                <li class="nav__item"><a href="#about" class="nav__link">About</a></li>
                <li class="nav__item"><a href="#skills" class="nav__link">Skills</a></li>
                <li class="nav__item"><a href="#portfolio" class="nav__link">Portfolio</a></li>
                <li class="nav__item"><a href="#contact" class="nav__link">Contact</a></li>
            </ul>
        </div>

        <div class="nav__toggle" id="nav-toggle">
            <i class='bx bx-menu'></i>
        </div>
    </nav>
</header>

<main class="l-main">
    <!--HOME-->
    <section class="home" id="home">
        <div class="home__container bd-grid">
            <h1 class="home__title"><span>{{ home.greet1 }}</span><br>{{ home.greet2 }}.</h1>

            <div class="home__scroll">
                <a href="#about" class="home__scroll-link"><i class='bx bx-up-arrow-alt'></i>Scroll down</a>
            </div>

            <img src="{% static 'assets/img/AI.png' %}" alt="" class="home__img">
        </div>
    </section>

    <!--ABOUT-->
    <section class="about section" id="about">
        <h2 class="section-title">About</h2>

        <div class="about__container bd-grid">
            <div class="about__img">

                <img src="{% static 'assets/img/AI.png' %}" alt="">
            </div>

            <div>
                <h2 class="about__subtitle">{{ about.heading }}</h2>
                <span class="about__profession">{{ about.career }}</span>
                <p class="about__text">{{ about.description }}</p>

                <div class="about__social">

                    {% for profile in about.profile_set.all %}
                    <a href="{{ profile.link }}" class="about__social-icon">
                        <i class='bx bxl-{{ profile.social_name }}'></i>
                    </a>
                    {% endfor %}

                </div>
            </div>
        </div>
    </section>

    <!--SKILLS-->
    <section class="skills section" id="skills">
        <h2 class="section-title">Skills</h2>

        <div class="skills__container bd-grid">
            <div class="skills__box">
                {% for category in categories %}
                <h3 class="skills__subtitle">{{category.name}}</h3>
                {% for skills in category.skills_set.all %}

                <span class="skills__name">{{skills.skill_name}}</span>
                {% endfor %}
                {% endfor %}

            </div>

            <div class="skills__img">
                <img src="{% static 'assets/img/img.png' %}" alt="">
            </div>
        </div>
    </section>

    <!--PORTFOLIO-->
    <section class="portfolio section" id="portfolio">
        <h2 class="section-title">Portfolio</h2>


        <div class="portfolio__container bd-grid">

            {% for portfolio in portfolios %}

            <div class="portfolio__img">
                <img src="{{ portfolio.image.url }}" alt="">

                <div class="portfolio__link">
                    <a href="{{ portfolio.link }}" class="portfolio__link-name">View details</a>
                </div>
            </div>

            {% endfor %}

        </div>

    </section>

    <!--CONTACT-->
    <section class="contact section" id="contact">
        <h2 class="section-title">Contact</h2>

        <div class="contact__container bd-grid">
            <div class="contact__info">
                <h3 class="contact__subtitle">EMAIL</h3>
                <span class="contact__text">aks@mail.com</span>

            </div>

            <div class="contact__info">

                <h3 class="contact__subtitle">PHONE</h3>
                <span class="contact__text">+9969690081</span>

            </div>


        </div>
    </section>
</main>

<!--FOOTER -->
<footer class="footer section">
    <div class="footer__container bd-grid">
        <div class="footer__data">
            <h2 class="footer__title">Ajay Kumar Sahu</h2>
            <p class="footer__text">I'm Ajay kumar Sahu and this is my portfolio website</p>
        </div>

        <div class="footer__data">
            <h2 class="footer__title">EXPLORE</h2>
            <ul>
                <li><a href="#home" class="footer__link">Home</a></li>
                <li><a href="#about" class="footer__link">About</a></li>
                <li><a href="#skills" class="footer__link">Skills</a></li>
                <li><a href="#portfolio" class="footer__link">Portfolio</a></li>
                <li><a href="#Contact" class="footer__link">Contact</a></li>
            </ul>
        </div>

        <div class="footer__data">
            <h2 class="footer__title">FOLLOW</h2>
            <a href="#" class="footer__social"><i class='bx bxl-facebook'></i></a>
            <a href="#" class="footer__social"><i class='bx bxl-instagram'></i></a>
            <a href="#" class="footer__social"><i class='bx bxl-twitter'></i></a>
        </div>


    </div>
</footer>
<!--===== SCROLL REVEAL =====-->
<script src="https://unpkg.com/scrollreveal"></script>

<!--===== MAIN JS =====-->
<script src="{% static 'assets/js/main.js' %}"></script>
</body>
</html>